version: “3”
services:
web:
image: nginx
deploy:
replicas: 2
restart_policy:
condition: on-failure
ports:
  - “80:80”
  - “443:443”
networks:
  - webnet
volumes:
  - path/to/my/app:app
  - path/to/nginx.conf:/etc/nginx/nginx.conf
  - path/to/site/conf:/etc/nginx/conf.d
